name: cart
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  geolocator: ^11.0.0
  http_image_provider:
  cached_network_image:
  url_launcher: ^6.0.9
  intl: ^0.17.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_secure_storage: ^5.0.0
  font_awesome_flutter: ^10.1.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/cartiey.jpeg"
  min_sdk_android: 21
  

flutter:
  uses-material-design: true
  assets:
      - images/
      - images/icons/check.png
      - images/icons/apple.png
      - images/icons/google.png
      - images/icons/facebook.png

  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
